version: 2.1

executors:
  newrelic_template:
    docker:
      - image: hashicorp/terraform:1.11.3@sha256:c2c17884347f9b5f3d71067a3ef1fb736f748979f89b35a2e4b5225735e7fe01
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  # For common
  fmt:
    executor: newrelic_template
    steps:
      - checkout
      - run:
          name: fmt
          command: terraform fmt -recursive -check ./

  # For aws template
  aws_plan:
    executor: newrelic_template
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          name: init
          command: cd ./aws/src/environments/<< parameters.env >> && terraform init -backend-config="backend.cfg"
      - run:
          name: plan
          command: cd ./aws/src/environments/<< parameters.env >> && terraform plan -var "nr_account_id=${NEWRELIC_ACCOUNT_ID}" -var "nr_api_key=${NEWRELIC_API_KEY}" -var "nr_license_key=${NEWRELIC_LICENSE_KEY}"
  aws_apply:
    executor: newrelic_template
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          name: init
          command: cd ./aws/src/environments/<< parameters.env >> && terraform init -backend-config="backend.cfg"
      - run:
          name: apply
          command: cd ./aws/src/environments/<< parameters.env >> && terraform apply -auto-approve -var "nr_account_id=${NEWRELIC_ACCOUNT_ID}" -var "nr_api_key=${NEWRELIC_API_KEY}" -var "nr_license_key=${NEWRELIC_LICENSE_KEY}"

  # For alert template
  alert_plan:
    executor: newrelic_template
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          name: init
          command: cd ./alert/src/environments/<< parameters.env >> && terraform init -backend-config="backend.cfg"
      - run:
          name: plan
          command: cd ./alert/src/environments/<< parameters.env >> && terraform plan -var "nr_account_id=${NEWRELIC_ACCOUNT_ID}" -var "nr_api_key=${NEWRELIC_API_KEY}"
  alert_apply:
    executor: newrelic_template
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          name: init
          command: cd ./alert/src/environments/<< parameters.env >> && terraform init -backend-config="backend.cfg"
      - run:
          name: apply
          command: cd ./alert/src/environments/<< parameters.env >> && terraform apply -auto-approve -var "nr_account_id=${NEWRELIC_ACCOUNT_ID}" -var "nr_api_key=${NEWRELIC_API_KEY}"

workflows:
  main:
    jobs:
      # For common
      - fmt

      # For aws template
      ## example
      - aws_plan:
          name: example_aws_plan
          env: example
          context: sre-eg-newrelic-template  # 事前に作成した Contexts 名を指定してください。
      - aws_apply_approve:
          name: example_aws_apply_approve
          requires:
            - example_aws_plan
          type: approval
          filters:
            branches:
              only:
                - main
      - aws_apply:
          name: example_aws_apply
          env: example
          context: sre-eg-newrelic-template  # 事前に作成した Contexts 名を指定してください。
          requires:
            - example_aws_apply_approve

      # For alert template
      ## example
      - alert_plan:
          name: example_alert_plan
          env: example
          context: sre-eg-newrelic-template  # 事前に作成した Contexts 名を指定してください。
          requires:
            - example_aws_plan
      - alert_apply_approve:
          name: example_alert_apply_approve
          requires:
            - example_aws_apply
            - example_alert_plan
          type: approval
          filters:
            branches:
              only:
                - main
      - alert_apply:
          name: example_alert_apply
          env: example
          context: sre-eg-newrelic-template  # 事前に作成した Contexts 名を指定してください。
          requires:
            - example_alert_apply_approve
